export default {
  PROFILES_RECEIVED: 'PROFILES_RECEIVED',
  PROFILE_CREATED: 'PROFILE_CREATED',
  PROFILE_SELECTED: 'PROFILE_SELECTED',
  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
  CURRENT_USER_LOGGEDOUT: 'CURRENT_USER_LOGGEDOUT',
  SAVE_BOOKMARK: 'SAVE_BOOKMARK',
  GET_BOOKMARKS: 'GET_BOOKMARKS'
}
